namespace Trp
{
	public enum TrpProfileId
	{
		Setup,
		LightingForward,
		Shadow,
		DepthNormals,
		OpaqueGeometry,
		Outline,
		TransparentGeometry,
		OitDraw,
		OitComposite,
		Skybox,
		CopyColorToOpaque,
		CopyColorToTransparent,
		CreateLut,
		CopyDepth,
		PostProcess,
		UberPostProcess,
		BlitBloomMipmaps,
		BloomComposite,
		LensFlareScreenSpace,
		LensFlareDataDrivenOcclusion,
		LensFlareDataDriven,
		FinalBlit,
		Ui,
		DebugForwardPlus,
		WireOverlay,
		Gizmo,
		CameraCapture,
	}
}